language: node_js
node_js:
  - '0.11'
before_install:
  ## TODO: Enable this
  ## - npm install -g grunt-cli
  - npm install
script:
  ## TODO: Enable this
  ## - npm run build
  - npm test
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  on:
    tags: true
notifications:
  email:
    - $GITHUB_EMAIL
